services:
  - type: web
    name: my-discord-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libopus0 ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python3 bot_music.py
